name: Deploy to Firebase
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}  # Accessing the secret
        run: |
          firebase deploy --only hosting --token $FIREBASE_API_KEY
